---
- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ hostvars[item]["ansible_fqdn"] }}$' line="{{ hostvars[item].ansible_all_ipv4_addresses[0] }} {{ hostvars[item].ansible_hostname }} {{ hostvars[item].ansible_fqdn }}" state=present
  when: hostvars[item].ansible_all_ipv4_addresses is defined
  with_items: "{{groups['all']}}"
